support for longformer (new 2023 request)
georgian-io/Multimodal-Toolkit pull request #47
Opened 2023-05-30 16:19 UTC by jtfields

I'm new to creating pull requests so please give me feedback if anything here is not correct.  I created the pull request comparing the Multimodal-Toolkit with the fork that I created.  I should also note that I had to downgrade transformers in my Colab notebook file to get the code to run (!pip install transformers==4.28.0).  Thanks again for all the help to get this to work and let me know if you have any questions.

2023-05-30 21:04 UTC, akashsaravanan-georgian requested changes
Hey @jtfields, thank you for all the help! I went through your code and suggested a few very minor changes. Would appreciate it if you could make those changes. I should be able to merge this into the repo after that!

2023-05-30 21:04 UTC, akashsaravanan-georgian commented on multimodal_transformers/model/tabular_combiner.py
Could we remove all the comments here? I think these might be leftover from your tests and may confuse future contributors.

2023-05-30 21:04 UTC, akashsaravanan-georgian commented on notebooks/text_w_tabular_classification.ipynb
Could you restore this notebook? We don't want this to be removed.

2023-05-30 21:04 UTC, akashsaravanan-georgian commented on notebooks/Longformer_text_w_tabular_classification_051823.ipynb
Could you rename this to remove the numbers at the end? Just use something like `longformer_text_w_tabular_classification.ipynb`

2023-05-30 21:04 UTC, akashsaravanan-georgian commented on setup.py
Could we revert the changes made here?

2023-05-31 14:31 UTC, jtfields commented on multimodal_transformers/model/layer_utils.py
I removed the commented line and the 3 new lines.

2023-05-31 14:33 UTC, jtfields commented on notebooks/Longformer_text_w_tabular_classification_051823.ipynb
I renamed the file.  You will need to compare the changes in the notebook with the original.  For example, I added a specific transformers version and used the metrics workaround for the bug in order to make the code run.

2023-05-31 14:39 UTC, jtfields commented on setup.py
I removed the changes from setup.py

2023-05-31 17:18 UTC, akashsaravanan-georgian approved these changes

2023-05-31 17:20 UTC, akashsaravanan-georgian commented
Great work @jtfields!! I'm merging the PR now. Out of curiosity, do you know why you had to downgrade transformers to get longformers working in the notebook?

2023-05-31 17:20 UTC, merged